/*!
 ******************************************************************************
 **
 ** \file main.c
 **
 ** \author FSLA AE Team
 **
 ** \version V0.10
 **
 ** \date 2011-11-24
 **
 ** \brief This file provides an example to compare the CRC codes 
 **        which are generated by hardware CRC module and software
 **        CRC arithmetic.
 **
 ** \attention THIS SAMPLE CODE IS PROVIDED AS IS. FUJITSU SEMICONDUCTOR
 **            ACCEPTS NO RESPONSIBILITY OR LIABILITY FOR ANY ERRORS OR
 **            OMMISSIONS.
 **
 ** (C) Copyright 200x-201x by Fujitsu Semiconductor(Shanghai) Co.,Ltd.
 **
 ******************************************************************************
 **
 ** \note Other information.
 **
 ******************************************************************************
 */

/*---------------------------------------------------------------------------*/
/* include files                                                             */
/*---------------------------------------------------------------------------*/
#include "mb9bf50x_lib.h"
#include "crc_sw.h"
/*---------------------------------------------------------------------------*/
/* local functions prototypes                                                */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/* global data                                                               */
/*---------------------------------------------------------------------------*/

/*!
 ******************************************************************************
 ** \brief  Main function of CRC calculation demo
 **
 ** \param  none
 **
 ** \retval uint32_t return value, if needed
 ******************************************************************************
 */

int32_t main(void)
{
    int8_t testData [10]= "1234567890";
    uint16_t hwCRC16Val, swCRC16Val;
    uint32_t hwCRC32Val, swCRC32Val;
    uint16_t crc16InitVal = 0xFFFF;
    uint32_t crc32InitVal = 0xFFFFFFFF;
    CRC_ConfigInfoT crcConfigInfo = {0};
    CRC_DataInfoT   crcDataInfo = {0};
    /*  
     *  Use hardware CRC16 to calculate crc16 code
     *  Check if it is same with that calcualted by software crc 
     */
    /* Set CRC parameter, CRC16 generator polynomial: 0x1021 */
    crcConfigInfo.CrcInfoBit.FinalXor = CRC_FINALXOR_OFF;
    crcConfigInfo.CrcInfoBit.ResultBitOrder = CRC_RESULT_BITORDER_MSB;
    crcConfigInfo.CrcInfoBit.ResultByteOrder = CRC_RESULT_BYTEORDER_BIG;
    crcConfigInfo.CrcInfoBit.BitOrder = CRC_BITORDER_MSB;
    crcConfigInfo.CrcInfoBit.ByteOrder = CRC_BYTEORDER_BIG;
    
    crcDataInfo.pData = (uint8_t*)testData;
    crcDataInfo.Width = CRC_INDATA_W_8;
    crcDataInfo.Num = sizeof(testData)/sizeof(int8_t);
    
    /* calculate CRC16 code by hardware CRC module */
    hwCRC16Val = CRC_CalcCRC16(&crcConfigInfo, &crcDataInfo, crc16InitVal);
    /* calculate CRC16 code by software arithmetic */
    swCRC16Val = CRC_SwCalCRC16((uint8_t*)testData, sizeof(testData)/sizeof(int8_t));
    /* are crc16 codes same ? */
    if(hwCRC16Val != swCRC16Val)
    {
        while(1);
    }
    
    /*  
     *  Use hardware CRC32 to calculate crc32 code
     *  Check if it is same with that calcualted by software crc 
     */
    /* Set CRC parameter, CRC32 generator polynomial: 0x04C11DB7 */
    crcConfigInfo.CrcInfoBit.FinalXor = CRC_FINALXOR_ON;
    crcConfigInfo.CrcInfoBit.ResultBitOrder = CRC_RESULT_BITORDER_MSB;
    crcConfigInfo.CrcInfoBit.ResultByteOrder = CRC_RESULT_BYTEORDER_BIG;
    crcConfigInfo.CrcInfoBit.BitOrder = CRC_BITORDER_MSB;
    crcConfigInfo.CrcInfoBit.ByteOrder = CRC_BYTEORDER_BIG;
    
    crcDataInfo.pData = (uint8_t*)testData;
    crcDataInfo.Width = CRC_INDATA_W_8;
    crcDataInfo.Num = sizeof(testData)/sizeof(int8_t);
    
    /* calculate CRC32 code by hardware CRC module */
    hwCRC32Val = CRC_CalcCRC32(&crcConfigInfo, &crcDataInfo, crc32InitVal);
    /* calculate CRC32 code by software arithmetic */
    swCRC32Val = CRC_SwCalCRC32((uint8_t*)testData, sizeof(testData)/sizeof(int8_t));
    /* are crc32 codes same ? */
    if(hwCRC32Val != swCRC32Val)
    {
        while(1);
    }
  
    while(1);
}


/*****************************************************************************/
/* END OF FILE */
